services:
  auth:
    build: ./auth
    volumes:
      - ./auth:/app
    environment:
      - DEBUG=1
    env_file:
      - ./auth/.env
    networks:
      - app_network

  video:
    build: ./video
    volumes:
      - ./video:/app
    environment:
      - DEBUG=1
    env_file:
      - ./video/.env
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - video
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 